apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: default
spec:
  project: default
  source:
    repoURL: willmendezcuemby/argo-test
    targetRevision: HEAD
    path: argoapp-test/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s